# Generated by Django 5.2.5 on 2025-10-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0007_alter_article_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_date', models.DateTimeField(auto_now_add=True)),
                ('categories', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-subscribed_date'],
            },
        ),
    ]
