# Generated by Django 5.2.5 on 2025-10-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0008_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
