# Generated by Django 5.2.5 on 2025-10-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0009_alter_subscriber_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('articles_count', models.IntegerField(default=0)),
                ('email_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
