# Generated by Django 5.2.5 on 2025-10-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_feed', '0010_articlebatch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleBatch',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.AddField(
            model_name='article',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
